from bottle import run, route, request, template, response, static_file, redirect
from collections import Counter
import json
import httplib2

# Libraries for Google Login
from oauth2client.client import OAuth2WebServerFlow
from oauth2client.client import flow_from_clientsecrets
from googleapiclient.errors import HttpError
from googleapiclient.discovery import build

# Python version: 3.5.6 (3.7)
# To run: type in 'python main_page.py'

# hold entire list of words that have been searched
total_list = Counter()

# holds list of words user inputted last
prev_list = Counter()


@route('/redirect')
def redirect_page():

    # User authorizes Google account access
    code = request.query.get('code', '')

    # Request access using the received code
    with open('client_secret.json', 'r') as read_file:
        data = json.load(read_file)
    data = data['web']

    flow = OAuth2WebServerFlow(client_id=data['client_id'],
                               client_secret=data['client_secret'],
                               scope=['https://www.googleapis.com/auth/plus.me',
                                      'https://www.googleapis.com/auth/userinfo.email'],
                               redirect_uri=data['redirect_uris'][0])

    # Exchange code for access token
    credentials = flow.step2_exchange(code)
    token = credentials.id_token['sub']

    # Retrieve data from Google (granted access) and store
    http = httplib2.Http()
    http = credentials.authorize(http)

    # Get user email
    users_service = build('oauth2', 'v2', http=http)
    user_document = users_service.userinfo().get().execute()
    user_email = user_document['email']

    return user_email


@route('/') 
def keywords():
    return template('website_template', user_input=None, keywords_list=[], popular_list=[], start_site=True)


@route('/', method='POST')
def display_keywords():

    # Enable user "Sign In" through google accounts
    if request.forms.get('SignIn') is not None:
        # Create Flow object from client_secrets.json
        flow = flow_from_clientsecrets('client_secret.json',
                                       scope=['https://www.googleapis.com/auth/plus.me',
                                              'https://www.googleapis.com/auth/userinfo.email'],
                                       redirect_uri='http://localhost:8080/redirect')

        # Retrieve authorization server URI generated by flow
        auth_uri = flow.step1_get_authorize_url()

        # Redirect user to auth_uri
        redirect(str(auth_uri))

    global total_list
    global prev_list
    num_words = 20

    keywords_input_raw = request.forms.get('keywords')

    # NOTE. form submissions may not only pertain to the search bar
    if keywords_input_raw is not None:
        # lower() makes it turn into lowercase
        # removed leading, ending and duplicate spaces
        keywords_input = " ".join(keywords_input_raw.split()).lower()

        # error checking for no user input
        if keywords_input == "":
            user_input = None
            keywords_list = prev_list

        else:
            user_input = keywords_input_raw

            # separating string into words and putting it into an array
            keywords_original_list = keywords_input.split(" ")

            # recording number of occurrences for each word
            keywords_list = Counter(keywords_original_list)
            prev_list = keywords_list

            total_list += keywords_list

        # take the top 20 most popular words
        popular_list = total_list.most_common(num_words)

    return template('website_template', user_input=user_input, keywords_list=keywords_list, popular_list=popular_list, start_site=False)


# Static CSS Files
@route('/static/<filename:re:.*\.css>')
def send_css(filename):
    return static_file(filename, root='static')


# Static jpg files
@route('/images/<filename:re:.*\.jpg>')
def send_img(filename):
    return static_file(filename, root="images")


run(host='localhost', port=8080, debug=True)


